name: Quarto render

on:
  push:
    branches:
      - main

jobs:
  quarto-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.LESSON_SUBMODULE_SYNC }}

      - name: Submodule init
        run: |
          git submodule init
          git submodule update --remote --recursive

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Quarto dependencies
        run: |
          python3 -m pip install jupyter

      - name: Render Quarto files
        run: quarto render -M embed-resources:true --output-dir output/

      - name: Commit and push rendered files
        env:
          DEST_REPO_TOKEN: ${{ secrets.LESSON_SUBMODULE_SYNC }}
          DEST_REPO: ${{ secrets.DEST_REPO }}
        if: ${{ env.DEST_REPO != '' }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

          git clone https://x-access-token:${{ env.DEST_REPO_TOKEN }}@github.com/${{ env.DEST_REPO }} ../dest_repo

          mkdir -p ../dest_repo/${{ github.event.repository.name }}
          rm -rf ../dest_repo/${{ github.event.repository.name }}/*
          cp -r output/* ../dest_repo/${{ github.event.repository.name }}/

          cd ../dest_repo
          git add .
          git commit -m "GitHub Actions: Rendered Quarto files" || true
          git push