name: Quarto render

on:
  push:
    branches:
      - main

jobs:
  quarto-render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto files
        run: quarto render -M embed-resources:true --output-dir output/

  external-send:
    needs: quarto-render
    runs-on: ubuntu-latest
    steps:
      - name: Commit and push rendered files
        env: 
          DEST_REPO: ${{ secrets.DEST_REPO }}
        if: ${{ env.DEST_REPO != '' }}
        run: |
          git config --global user.email ${{ github.event.pusher.email || 'default@example.com' }}
          git config --global user.name ${{ github.event.pusher.name || 'default-username'}}
          git clone ${{ secrets.DEST_REPO }} ../dest_repo
          mkdir -p ../dest_repo/${{ github.event.repository.name }}
          rm -rf ../dest_repo/${{ github.event.repository.name }}/*
          cp output/* ../dest_repo/${{ github.event.repository.name }}
          cd ../dest_repo
          git add .
          git commit -m "GitHub Actions: Rendered Quarto files"
          git push